"""initial schema from erd

Revision ID: 17e2b4e7a636
Revises: 
Create Date: 2026-08-25 18:32:08.429285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17e2b4e7a636'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_actions',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('close_reason_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('contact_methods',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('department_types',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('handoff_statuses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('incident_severities',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('incident_statuses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('incident_types',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('incident_urgencies',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('media_kinds',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('notification_channels',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('notification_event_types',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('resolution_outcomes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('verification_methods',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('verification_statuses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('departments',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_code'], ['department_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('ix_departments_active', ['active'], unique=False)
        batch_op.create_index('ix_departments_name', ['name'], unique=False)
        batch_op.create_index('ix_departments_type_code', ['type_code'], unique=False)

    op.create_table('incident_status_transitions',
    sa.Column('from_code', sa.String(), nullable=False),
    sa.Column('to_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_code'], ['incident_statuses.code'], ),
    sa.ForeignKeyConstraint(['to_code'], ['incident_statuses.code'], ),
    sa.PrimaryKeyConstraint('from_code', 'to_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role_code', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('id_verified', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['preferred_contact_method'], ['contact_methods.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_id_verified_created', ['id_verified', 'created_at'], unique=False)
        batch_op.create_index('ix_users_role_code', ['role_code'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('urgency_code', sa.String(), nullable=False),
    sa.Column('severity_code', sa.String(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('reporter_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('reporter_email', sa.String(), nullable=True),
    sa.Column('reporter_phone', sa.String(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(), nullable=True),
    sa.Column('close_reason_code', sa.String(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolution_outcome_code', sa.String(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('resolved_by_name', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archive_reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['close_reason_code'], ['close_reason_codes.code'], ),
    sa.ForeignKeyConstraint(['preferred_contact_method'], ['contact_methods.code'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolution_outcome_code'], ['resolution_outcomes.code'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['severity_code'], ['incident_severities.code'], ),
    sa.ForeignKeyConstraint(['status_code'], ['incident_statuses.code'], ),
    sa.ForeignKeyConstraint(['type_code'], ['incident_types.code'], ),
    sa.ForeignKeyConstraint(['urgency_code'], ['incident_urgencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('idx_incidents_coords', ['lat', 'lng'], unique=False)
        batch_op.create_index('idx_incidents_inbox', ['archived', 'status_code', 'created_at'], unique=False)
        batch_op.create_index('idx_incidents_status_created', ['status_code', 'created_at'], unique=False)
        batch_op.create_index('idx_incidents_urgency_created', ['urgency_code', 'created_at'], unique=False)
        batch_op.create_index('ix_incidents_archived', ['archived'], unique=False)
        batch_op.create_index('ix_incidents_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_incidents_reporter_id', ['reporter_id'], unique=False)
        batch_op.create_index('ix_incidents_severity_code', ['severity_code'], unique=False)
        batch_op.create_index('ix_incidents_status_code', ['status_code'], unique=False)
        batch_op.create_index('ix_incidents_type_code', ['type_code'], unique=False)
        batch_op.create_index('ix_incidents_urgency_code', ['urgency_code'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('incident_reference', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('actor_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('action_code', sa.String(), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_code'], ['audit_actions.code'], ),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_action_code', ['action_code'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_audit_logs_incident_id', ['incident_id'], unique=False)

    op.create_table('incident_department_handoffs',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('department_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('initiated_by_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('initiated_by_name', sa.String(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('handed_off_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_code'], ['handoff_statuses.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'department_id', name='uq_handoff_incident_department')
    )
    with op.batch_alter_table('incident_department_handoffs', schema=None) as batch_op:
        batch_op.create_index('ix_handoffs_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_handoffs_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_handoffs_initiated_by_id', ['initiated_by_id'], unique=False)
        batch_op.create_index('ix_handoffs_status_code', ['status_code'], unique=False)

    op.create_table('incident_media',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('kind_code', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kind_code'], ['media_kinds.code'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_media', schema=None) as batch_op:
        batch_op.create_index('idx_media_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index('ix_incident_media_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_incident_media_kind_code', ['kind_code'], unique=False)
        batch_op.create_index('ix_incident_media_uploaded_by_id', ['uploaded_by_id'], unique=False)

    op.create_table('incident_notes',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_notes', schema=None) as batch_op:
        batch_op.create_index('idx_notes_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index('ix_incident_notes_author_id', ['author_id'], unique=False)
        batch_op.create_index('ix_incident_notes_incident_id', ['incident_id'], unique=False)

    op.create_table('incident_status_history',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('from_status_code', sa.String(), nullable=True),
    sa.Column('to_status_code', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('actor_name', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_status_code'], ['incident_statuses.code'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_status_code'], ['incident_statuses.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_status_history', schema=None) as batch_op:
        batch_op.create_index('idx_history_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index('ix_incident_status_history_actor_id', ['actor_id'], unique=False)
        batch_op.create_index('ix_incident_status_history_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_incident_status_history_to_status_code', ['to_status_code'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('recipient_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('channel_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_code'], ['notification_channels.code'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_code'], ['notification_event_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_inbox', ['recipient_id', 'read', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_channel_code', ['channel_code'], unique=False)
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_id', ['recipient_id'], unique=False)
        batch_op.create_index('ix_notifications_type_code', ['type_code'], unique=False)

    op.create_table('reporter_verifications',
    sa.Column('id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('incident_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=False),
    sa.Column('status_code', sa.String(), nullable=False),
    sa.Column('method_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.Uuid().with_variant(postgresql.UUID(as_uuid=True), 'postgresql'), nullable=True),
    sa.Column('verified_by_name', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['method_code'], ['verification_methods.code'], ),
    sa.ForeignKeyConstraint(['status_code'], ['verification_statuses.code'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reporter_verifications', schema=None) as batch_op:
        batch_op.create_index('idx_verifications_incident_created', ['incident_id', 'created_at'], unique=False)
        batch_op.create_index('ix_reporter_verifications_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_reporter_verifications_status_code', ['status_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reporter_verifications', schema=None) as batch_op:
        batch_op.drop_index('ix_reporter_verifications_status_code')
        batch_op.drop_index('ix_reporter_verifications_incident_id')
        batch_op.drop_index('idx_verifications_incident_created')

    op.drop_table('reporter_verifications')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_type_code')
        batch_op.drop_index('ix_notifications_recipient_id')
        batch_op.drop_index('ix_notifications_incident_id')
        batch_op.drop_index('ix_notifications_created_at')
        batch_op.drop_index('ix_notifications_channel_code')
        batch_op.drop_index('idx_notifications_inbox')

    op.drop_table('notifications')
    with op.batch_alter_table('incident_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_status_history_to_status_code')
        batch_op.drop_index('ix_incident_status_history_incident_id')
        batch_op.drop_index('ix_incident_status_history_actor_id')
        batch_op.drop_index('idx_history_incident_created')

    op.drop_table('incident_status_history')
    with op.batch_alter_table('incident_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_notes_incident_id')
        batch_op.drop_index('ix_incident_notes_author_id')
        batch_op.drop_index('idx_notes_incident_created')

    op.drop_table('incident_notes')
    with op.batch_alter_table('incident_media', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_media_uploaded_by_id')
        batch_op.drop_index('ix_incident_media_kind_code')
        batch_op.drop_index('ix_incident_media_incident_id')
        batch_op.drop_index('idx_media_incident_created')

    op.drop_table('incident_media')
    with op.batch_alter_table('incident_department_handoffs', schema=None) as batch_op:
        batch_op.drop_index('ix_handoffs_status_code')
        batch_op.drop_index('ix_handoffs_initiated_by_id')
        batch_op.drop_index('ix_handoffs_incident_id')
        batch_op.drop_index('ix_handoffs_department_id')

    op.drop_table('incident_department_handoffs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_incident_id')
        batch_op.drop_index('ix_audit_logs_entity_type')
        batch_op.drop_index('ix_audit_logs_entity_id')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_actor_id')
        batch_op.drop_index('ix_audit_logs_action_code')
        batch_op.drop_index('idx_audit_incident_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_urgency_code')
        batch_op.drop_index('ix_incidents_type_code')
        batch_op.drop_index('ix_incidents_status_code')
        batch_op.drop_index('ix_incidents_severity_code')
        batch_op.drop_index('ix_incidents_reporter_id')
        batch_op.drop_index('ix_incidents_created_at')
        batch_op.drop_index('ix_incidents_archived')
        batch_op.drop_index('idx_incidents_urgency_created')
        batch_op.drop_index('idx_incidents_status_created')
        batch_op.drop_index('idx_incidents_inbox')
        batch_op.drop_index('idx_incidents_coords')

    op.drop_table('incidents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_code')
        batch_op.drop_index('ix_users_id_verified_created')

    op.drop_table('users')
    op.drop_table('incident_status_transitions')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('ix_departments_type_code')
        batch_op.drop_index('ix_departments_name')
        batch_op.drop_index('ix_departments_active')

    op.drop_table('departments')
    op.drop_table('verification_statuses')
    op.drop_table('verification_methods')
    op.drop_table('roles')
    op.drop_table('resolution_outcomes')
    op.drop_table('notification_event_types')
    op.drop_table('notification_channels')
    op.drop_table('media_kinds')
    op.drop_table('incident_urgencies')
    op.drop_table('incident_types')
    op.drop_table('incident_statuses')
    op.drop_table('incident_severities')
    op.drop_table('handoff_statuses')
    op.drop_table('department_types')
    op.drop_table('contact_methods')
    op.drop_table('close_reason_codes')
    op.drop_table('audit_actions')
    # ### end Alembic commands ###
